export const P2P_REQUIRED_COLUMNS = [
  'Company Code',
  'Plant',
  'Delivery Cost.',
  'Storage Location',
  'PR Document Type',
  'PR Date',
  'PR Number',
  'PR Item Number',
  'PR Quantity',
  'PR UOM',
  'PO Document Type',
  'PO Date',
  'PO Number',
  'PO Item Number',
  'PO Advance Document No',
  'PO Advance Document Date',
  'PO Advance Assignment',
  'Payment Term',
  'Payment Term Description',
  'Advance Text',
  'Supplier',
  'Supplier Name',
  'Material',
  'Material Description',
  'PO Quantity',
  'PO UOM',
  'Exchange Rate',
  'Net Price/Unit',
  'Curr Key',
  'PO Amount',
  'State Code',
  'HSN/SAC',
  'CGST Rate',
  'CGST Amount',
  'SGST Rate',
  'SGST Amount',
  'IGST Rate',
  'IGST Amount',
  'Vendor GSTIN',
  'Material Document',
  'MD.Year',
  'MD Date',
  'GR Quantity',
  'GR UOM',
  'Mov Type',
  'MM Inv.Doc.No.',
  'Inv.Date',
  'Gross Amount',
  'Acc.Inv.Doc.No.',
  'Inv.Posting Date',
  'BOE',
  'BOE Date',
  'BOL Date',
  'Delivery Agent',
  'Vessel Name',
  'Voyage No',
  'PO LC No',
  'MIGO LC No',
  'Payment.Doc.No',
  'Payment Date',
  'Assignment',
  'Item Text'
];

export const PURCHASE_REQUIRED_COLUMNS = [
  'Country/Region Key',
  'Company Code',
  'Vendor',
  'Name 1',
  'City',
  'Region',
  'ECC No.',
  'Excise Registration No.',
  'Excise Range',
  'Excise Division',
  'Excise Commissionerate',
  'CST number',
  'LST number',
  'Permanent account number',
  'Service Tax Registration Number',
  'Purchasing Document',
  'Document Date',
  'Purch. Doc. Category',
  'Purchasing Doc. Type',
  'Purch. organization',
  'Purchasing Group',
  'Payment terms',
  'Incoterms',
  'Incoterms (Part 2)',
  'Material Document',
  'Material Doc. Year',
  'Posting Date',
  'Trans./Event Type',
  'Document Type',
  'Excise transaction type',
  'Internal Excise Document No.',
  'Plant',
  'Excise Group',
  'Series Group',
  'Sub Transaction Type',
  'Official Excise Document No.',
  'Excise document date',
  'Excise year',
  'Currency',
  'BED',
  'SED',
  'AED',
  'CESS',
  'Reference document 1',
  'Status',
  'CENVAT Utilization status',
  'NCCD Value',
  'ECS',
  'Additional tax1',
  'Additional tax2',
  'Additional tax3',
  'Register entry serial no.',
  'Accounting document',
  'Invoice Document No.',
  'Fiscal Year',
  'Posting Date',
  'Currency',
  'Gross Invoice Amount',
  'Unplanned Del. Costs',
  'Total Tax Amount',
  'Tax Code',
  'Invoice doc. status',
  'Document Number',
  'Business place',
  'Section Code'
];

export const SALES_REQUIRED_COLUMNS = [
  'GL Code',
  'Sales Org',
  'Plant',
  'Customer Code',
  'Customer Name',
  'Customer Reference',
  'Type',
  'Document Type',
  'Sales Doc No',
  'Sales Doc Date',
  'Sales Order No',
  'Sales Order Date',
  'Item Code',
  'Item Name',
  'Quantity',
  'Unit Price',
  'Quantity x Price',
  'CGST',
  'SGST',
  'IGST',
  'Document Total',
  'WP',
  'Mega Watts',
  'Price Unit(Price/WP)',
  'Delivery Challan Doc No',
  'Delivery Challan Doc Date',
  'Billing Doc.No',
  'LR No',
  'LR Date',
  'Vehicle No',
  'Transporter Name',
  'Transporter Contact No.',
  'Sales Employee',
  'Sales Emp.Name',
  'Segment',
  'Product Type',
  'Company Code',
  'Billing type',
  'Division',
  'Distribution Channel',
  'Sales FI Doc No',
  'Sales Posting Date',
  'Sales Creation Date',
  'Delivery Challan FI Doc No',
  'Delivery Challan Posting Date',
  'PO number (Customer reference)',
  'SO.Item No.',
  'Sales Person',
  'FY Year',
  'FY_Quarter',
  'CY_Quarter',
  'City',
  'Region',
  'Bill To_GSTIN',
  'Ship To_GSTIN',
  'PAN Number',
  'Item Number',
  'Profit Center',
  'Profit Center Name',
  'Business Place',
  'Material type',
  'Material Group',
  'Item GROUP',
  'HSN',
  'Currency Type',
  'Ex Rate',
  'Line Discount%',
  'Line Discount Amount',
  'After Discount',
  'Tax Code',
  'Freight',
  'Insurance',
  'TCS Rate',
  'TCS Amount',
  'TCS Section',
  'GST Rate',
  'IRN Number',
  'IRN date',
  'IRN Generation Date',
  'IRN Acknowledgment No',
  'E-way Bill No',
  'E-way Bill Dat',
  'Sold to Party Code',
  'Sold to party Name',
  'Sold to Party Address',
  'Sold to Party Region',
  'Sold to Party Postal Code',
  'Sold to Party City',
  'Ship to Party Code',
  'Ship to Party Name',
  'Ship to Party Address',
  'Ship to Party Region',
  'Ship to Party Postal Code',
  'Ship to Party City',
  'Unit of Measure',
  'Cancelled billing Doc.No',
  'Incoterms',
  'Terms of payment',
  'SO Created By'
];

export const convertToTextFile = (data: any[], filename: string) => {
  if (data.length === 0) {
    return;
  }

  // Get all column headers
  const headers = Object.keys(data[0]);
  
  // Create header row
  let textContent = headers.join('\t') + '\n';
  
  // Add data rows
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header];
      return value !== null && value !== undefined ? String(value) : '';
    });
    textContent += values.join('\t') + '\n';
  });

  // Create and download file
  const blob = new Blob([textContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const getFormattedDateTime = () => {
  const now = new Date();
  return now.toISOString().replace(/[:.]/g, '-').slice(0, -5);
};